### ISSUE TITLE
i can't run the loopertrx.py

### ISSUE THREAD

**Issue by elberino** [reinerh/loopertrx#3]
I do not know much about programming (I'm just a student) but when I call loopertrx, it shows this:

`elber@deep-thought:~/Downloads/loopertrx-master$ ./loopertrx.py
Traceback (most recent call last):
  File "./loopertrx.py", line 173, in <module>
    class Gui(Frame):
NameError: name 'Frame' is not defined
elber@deep-thought:~/Downloads/loopertrx-master$ python loopertrx.py
  File "loopertrx.py", line 239
    print(msg, end='', flush=True)
                  ^
SyntaxError: invalid syntax
elber@deep-thought:~/Downloads/loopertrx-master$ `

Is there something I'm doing wrong?
I read that to execute the file would have to give chmod permission

**Comment by reinerh** [comment]
`$ python loopertrx.py`
This will run the script with Python 2, but it requires Python 3. So if you want to start it this way, please use `$ python3 loopertrx.py`.

Regarding the other error (`NameError: name 'Frame' is not defined`), I currently don't have a real idea. It might be related to one of the dependencies?
Does the following work for your:
```
$ python3
>>> from tkinter import Frame
>>>
```
Or does it also show an error?
